sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=dav
    - TC=unit
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP_NAME

before_script:
  - cd apps/$APP_NAME

script:
  - bash tests/travis/$TC.sh

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=mysql;TC=litmus
    - php: 5.4
      env: DB=mysql;TC=lint

  allow_failures:
    - php: hhvm
  fast_finish: true
